version: "3.0"
services:
    dockerapp:
        extends:
            file: common.yml
            service: dockerapp
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - redis
    redis:
        extends:
            file: common.yml
            service: redis
