version: "3.0"
services:
    dockerapp:
        image: juannavasjn/dockerapp
        ports:
            - "4000:5000"
        depends_on:
            - redis
        deploy:
            replicas: 1
    redis:
        image: redis:3.2.0
